ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.05
    smooth_lagged_data: true
    history_length: 1.0

    # Marcos de referencia
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true

    # INPUT 1: IMU DE LA PIXHAWK
    imu0: /mavros/imu/data
    imu0_config: [false, false, false,  # X, Y, Z
                  true,  true,  true,   # Roll, Pitch, Yaw
                  false, false, false,  # Velocidad lineal
                  true,  true,  true,   # Velocidad angular
                  false, false, false]  # Aceleración

    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # INPUT 2: ODOMETRÍA VISUAL (RTAB-Map)
    odom0: /rtabmap/odom
    odom0_config: [true,  true,  true,   # X, Y, Z
                   false, false, false,  # Roll, Pitch, Yaw
                   false, false, false,  # Velocidad lineal
                   false, false, false,  # Velocidad angular
                   false, false, false]  # Aceleración

    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    
    # IMPORTANTE: Para que no haya conflictos de tiempo en simulación
    use_sim_time: true